name: Tag and Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull latest changes
        run: git pull origin main
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          push: true
          tags: ghcr.io/allenneuraldynamics/anivia:latest
  update_ecs_service :
    runs-on: ubuntu-latest
    needs: publish
    permissions:
      id-token: write
      contents: read
    env:
      ECS_ROLE: ${{ secrets.AWS_ANIVIA_ECS_ROLE }}
      AWS_REGION : ${{ vars.AWS_REGION_DEV }}
      ECS_CLUSTER : ${{ vars.AWS_ANIVIA_ECS_CLUSTER }}
      ECS_SERVICE : ${{ vars.AWS_ANIVIA_ECS_SERVICE }}
    steps:
      - uses: actions/checkout@master
      - name: Pull latest changes
        run: git pull origin main
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.ECS_ROLE }}
          role-session-name: github-ecs-update-service
          aws-region: ${{ env.AWS_REGION }}
      - name: Update ECS service
        run: |
          python -m pip install awscli
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
